/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import modelo.Usuarios;
import controlador.CrudArchivos;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author adrian
 */
public class PantallaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form PantallaRegistro
     */
    public PantallaRegistro() {
        initComponents();
        setTitle("InteliAccounting Registrar Usuarios");

    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioNivelAccs = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        textApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textLoginUsr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textPass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        opcNormal = new javax.swing.JRadioButton();
        opcAdmin = new javax.swing.JRadioButton();
        btAnadir = new javax.swing.JButton();
        textPass2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Crear nuevo usuario :");

        jLabel3.setText("Tu nombre:");

        jLabel4.setText("Apellidos :");

        textApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textApellidosActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre de usuario :");

        jLabel6.setText("Nivel de acceso :");

        jLabel7.setText("Contrasena :");

        jLabel8.setText("Opcional :");

        jLabel9.setText("Correo Electronico :");

        jLabel10.setText("Confirmar contrasena :");

        radioNivelAccs.add(opcNormal);
        opcNormal.setText("Normal");
        opcNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcNormalActionPerformed(evt);
            }
        });

        radioNivelAccs.add(opcAdmin);
        opcAdmin.setText("Admin");

        btAnadir.setText("Anadir");
        btAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textEmail))
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textLoginUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(textApellidos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textPass2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opcNormal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opcAdmin))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textLoginUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(opcNormal)
                    .addComponent(opcAdmin))
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textApellidosActionPerformed

    private void opcNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcNormalActionPerformed
       
    }//GEN-LAST:event_opcNormalActionPerformed

    private void btAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnadirActionPerformed
        String opcRadio1="";
        
        //Funciones del nivel de acceso
        if(opcNormal.isSelected()){
            opcRadio1=opcNormal.getText();
        }
        else if (opcAdmin.isSelected()){
            opcRadio1=opcAdmin.getText();
        }
        
        
        if(textLoginUsr.getText().isBlank() || txtNom.getText().isBlank() || textApellidos.getText().isBlank() || textPass.getPassword().length == 0 || textPass2.getPassword().length == 0 || opcRadio1.isBlank() ){
            JOptionPane.showMessageDialog(null,"Has dejado un campo vacio :o");
            
        }
        
        String loginUsr = textLoginUsr.getText().trim();
        
        String nombreUsr = txtNom.getText().trim();
        String apellidos = textApellidos.getText().trim();
        String email ="";
        
        if(textEmail.getText().isBlank()){
            email="Desconocido";
        }
        else {
             email = textEmail.getText();
        }
        
       
        
        
        
               
        char[] Password1 =textPass.getPassword();
        String Password="a" ;
        char[] Password2=textPass2.getPassword();
        boolean tieneMayus=false;
        boolean tieneDig=false;
        
        /*Con este for recorremos Password para saber si tiene alguna mayuscula ,
        si tiene la variable tieneMayus sera verdadera o true*/
        for(int a=0; a<Password1.length;a++){
            char letra=Password1[a];
            if(Character.isUpperCase(letra)){
                tieneMayus=true;
                break;
            }
        }
        
        /*Con este for recorremos Password para saber si tiene algun Digito ,
        si tiene, la variable tieneDig sera verdadera o true*/
        for(int a=0; a<Password1.length;a++){
            char letra=Password1[a];
            if(Character.isDigit(letra)){
                tieneDig=true;
                break;
            }
        }
        
        
        if(Password1.length < 8 || tieneMayus == false || tieneDig == false){
            JOptionPane.showMessageDialog(null,"La constrasena debe tener al menos 8 caracteeres, una mayuscula y un numero");
        }
        
        //Confirmar contrasena NOTA: Las contrasena son arreglos de caracteres no pueden ser string por tema de seguridad
        
        if (Arrays.equals(Password1, Password2)) {
            Password = new String(Password2);
           
            
            
            }
        else{
            JOptionPane.showMessageDialog(null ,"Contrasena invalida");
        }
        
        Usuarios usuario = new Usuarios();
        usuario.setLoginUsr(loginUsr);
        usuario.setNombreUs(nombreUsr);
        usuario.setApellidosUsr(apellidos);
        usuario.setNivelAccs(opcRadio1);
        usuario.setEmailUsr(email);
        usuario.setPassUsr(Password);

    // Guardar el usuario en el archivo de texto
    CrudArchivos.guardarUsuarioEnArchivo(usuario);
        
    }//GEN-LAST:event_btAnadirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    dispose(); // Cierra la ventana secundaria sin afectar la ventana principal
    }//GEN-LAST:event_formWindowClosing

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnadir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton opcAdmin;
    private javax.swing.JRadioButton opcNormal;
    private javax.swing.ButtonGroup radioNivelAccs;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textLoginUsr;
    private javax.swing.JPasswordField textPass;
    private javax.swing.JPasswordField textPass2;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
